### ISSUE TITLE
`getNativeScrollRef` is not a function

### ISSUE THREAD

**Issue by tamagokun** [necolas/react-native-web#1560]
**The problem**

Rendering a fairly complex set of virtualized lists (VirtualizedList -> ScrollView(horizontal) -> SectionList), which renders perfectly, however somewhere down the line I get an error.

The list isn't able to scroll vertically, so i'm assuming that this error is related to that.

```
react_devtools_backend.js:6 measureLayoutRelativeToContainingList threw an error TypeError: this.context.virtualizedList.getOutermostParentListRef(...).getScrollRef(...).getNativeScrollRef is not a function
```

Looks like the scrollRef doesn't have a `getNativeScrollRef` function.

**How to reproduce**

Simplified test case: https://codesandbox.io/s/blissful-yonath-dh2ot

Steps to reproduce:
1.
2.
3.

**Expected behavior**

react-native-web supports this and can render lists properly.

**Environment (include versions). Did this work in previous versions?**

* React Native for Web (version): 0.12.2
* React (version): 16.9.0
* Browser: Chrome

Looks like this worked OK with 0.11.0, but is failing in 0.12.2

**Comment by necolas** [comment]
Probably need to add new methods to `ScrollView` - https://github.com/facebook/react-native/blob/c0d8c1db9077d08c3832b23e959bf70ad204307d/Libraries/Components/ScrollView/ScrollView.js#L790

**Comment by tamagokun** [comment]
i've opened up a PR to fix the initial problem, but I don't know what might need to change in ScrollResponder. Do you tend to copy things over 1:1 from react-native? Or perhaps you can point out what might need to be updated?

**Comment by whereiscode** [comment]
react_devtools_backend.js:6 measureLayoutRelativeToContainingList threw an error TypeError: this.context.virtualizedList.getOutermostParentListRef(...).getScrollRef(...).getNativeScrollRef is not a function
    at VirtualizedList.measureLayoutRelativeToContainingList (http://localhost:8001/a/umi.js:70402:30998)
    at VirtualizedList._onCellLayout (http://localhost:8001/a/umi.js:70402:30641)
    at onLayout (http://localhost:8001/a/umi.js:70402:22667)
    at http://localhost:8001/a/umi.js:69700:3579
    at http://localhost:8001/a/umi.js:69413:1394


I had a similar problem when the list was large
