### ISSUE TITLE
Cannot find module 'react/lib/findDOMNode' from 'index.js'

### ISSUE THREAD

**Issue by sibelius** [necolas/react-native-web#265]
I'm receiving the below error when I try to use jest-html with react-native-web - https://github.com/guigrpa/jest-html/issues/1#issuecomment-262935287

```jsx
Cannot find module 'react/lib/findDOMNode' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:151:17)
      at Object.<anonymous> (node_modules/react-native-web/dist/modules/findNodeHandle/index.js:1:164)
      at Object.<anonymous> (node_modules/react-native-web/dist/index.js:1:110)

```
**Environment (include versions)**

OS: Mac OS Sierra
Browser: Chrome
React Native for Web (version): ^0.0.55
React (version): 15.4.0-rc.4

**Comment by MoOx** [comment]
Does not work with React 15.4.x yet. See #255.
